// <auto-generated />
using HOT2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOT2.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOT2.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Vehicle"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Office"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("HOT2.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 0,
                            Description = "Great for throwing around or even hitting",
                            ImageUrl = "baseball.png",
                            Name = "Baseball",
                            Price = 3m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 0,
                            Description = "Great for getting around your town or even skating on a rink",
                            ImageUrl = "rollerSkate.png",
                            Name = "Roller Skates",
                            Price = 14m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 0,
                            Description = "Reliable Car that will last a lifetime",
                            ImageUrl = "toyota.png",
                            Name = "Toyota Camary",
                            Price = 24199.99m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 0,
                            Description = "Able to do work and play games on",
                            ImageUrl = "Computer.png",
                            Name = "Computer",
                            Price = 800m,
                            Quantity = 0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 0,
                            Description = "Pairs great with a office space and will make your back and butt not hurt after a long work day",
                            ImageUrl = "chair.png",
                            Name = "Chair",
                            Price = 50m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("HOT2.Models.Product", b =>
                {
                    b.HasOne("HOT2.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
