// <auto-generated />
using System;
using HOT3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOT3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOT3.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HOT3.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Home & Office"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Gaming"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Fitness"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("HOT3.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HOT3.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HOT3.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Noise-cancelling over-ear headphones",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1678099940967-73fe30680949?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8d2lyZWxlc3MlMjBoZWFkcGhvbmVzfGVufDB8fDB8fHww",
                            Name = "Wireless Bluetooth Headphones",
                            Price = 89.99m,
                            StockQuantity = 42
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3,
                            Description = "27-inch IPS display",
                            ImageUrl = "https://images.unsplash.com/photo-1551645120-d70bfe84c826?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bW9uaXRvcnxlbnwwfHwwfHx8MA%3D%3D",
                            Name = "4K Ultra HD Monitor",
                            Price = 279.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "RGB backlit mechanical keyboard",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1664194583917-b0ba07c4ce2a?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Z2FtaW5nJTIwa2V5Ym9hcmR8ZW58MHx8MHx8fDA%3D",
                            Name = "Mechanical Gaming Keyboard",
                            Price = 74.50m,
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Adjustable lumbar support",
                            ImageUrl = "https://images.unsplash.com/photo-1688578735427-994ecdea3ea4?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b2ZmaWNlJTIwY2hhaXJ8ZW58MHx8MHx8fDA%3D",
                            Name = "Ergonomic Office Chair",
                            Price = 159.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "45W fast charging adapter",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1669262667978-5d4aafe29dd5?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dXNiLWMlMjBjaGFyZ2VyfGVufDB8fDB8fHww",
                            Name = "USB-C Fast Charger",
                            Price = 24.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Description = "WiFi-enabled color bulb",
                            ImageUrl = "https://media.istockphoto.com/id/1215074546/photo/controlling-light-bulb-with-mobile-device.webp?a=1&b=1&s=612x612&w=0&k=20&c=n-PD48Q5qUJKY8dVCSU-7OVBiquG557pf7iCwMNGa7M=",
                            Name = "Smart LED Light Bulb",
                            Price = 14.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "Water-resistant outdoor speaker",
                            ImageUrl = "https://images.unsplash.com/photo-1589256469067-ea99122bbdc4?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Ymx1ZXRvb3RoJTIwc3BlYWtlcnxlbnwwfHwwfHx8MA%3D%3D",
                            Name = "Portable Bluetooth Speaker",
                            Price = 49.99m,
                            StockQuantity = 33
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 5,
                            Description = "Fits up to 17-inch laptops",
                            ImageUrl = "https://images.unsplash.com/photo-1667411424771-cadd97150827?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGFwdG9wJTIwYmFja3BhY2t8ZW58MHx8MHx8fDA%3D",
                            Name = "Laptop Backpack",
                            Price = 39.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 5,
                            Description = "Insulated 32oz bottle",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1681284938505-62efa3494bf2?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c3RhaW5sZXNzJTIwc3RlZWwlMjB3YXRlciUyMGJvdHRsZXxlbnwwfHwwfHx8MA%3D%3D",
                            Name = "Stainless Steel Water Bottle",
                            Price = 19.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            Description = "Silent-click ergonomic mouse",
                            ImageUrl = "https://images.unsplash.com/photo-1707592691247-5c3a1c7ba0e3?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8d2lyZWxlc3MlMjBtb3VzZXxlbnwwfHwwfHx8MA%3D%3D",
                            Name = "Wireless Mouse",
                            Price = 17.99m,
                            StockQuantity = 95
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            Description = "Tracks heart rate and steps",
                            ImageUrl = "https://images.unsplash.com/photo-1678356717973-f2177782388a?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Zml0dG5lc3MlMjB3YXRjaHxlbnwwfHwwfHx8MA%3D%3D",
                            Name = "Smart Fitness Watch",
                            Price = 129.99m,
                            StockQuantity = 28
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            Description = "1080p USB webcam",
                            ImageUrl = "https://images.unsplash.com/photo-1704364610940-52b509d3951f?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aGQlMjB3ZWJjYW18ZW58MHx8MHx8fDA%3D",
                            Name = "HD Webcam",
                            Price = 59.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 1,
                            Description = "Portable USB 3.0 drive",
                            ImageUrl = "https://media.istockphoto.com/id/1364094222/photo/backup-your-software.webp?a=1&b=1&s=612x612&w=0&k=20&c=JKeYdUxEBpP8tCI80CQXg59Yc0zbmEm_tSI3bQcdGp0=",
                            Name = "External Hard Drive 2TB",
                            Price = 69.99m,
                            StockQuantity = 34
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 5,
                            Description = "Adjustable brightness",
                            ImageUrl = "https://images.unsplash.com/photo-1621177555452-bedbe4c28879?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZGVzayUyMGxhbXB8ZW58MHx8MHx8fDA%3D",
                            Name = "LED Desk Lamp",
                            Price = 22.99m,
                            StockQuantity = 48
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 1,
                            Description = "In-ear wired earbuds",
                            ImageUrl = "https://images.unsplash.com/photo-1733641839465-f9de0c9b9bde?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bm9pc2UlMjBjYW5jZWxsaW5nJTIwZWFyYnVkc3xlbnwwfHwwfHx8MA%3D%3D",
                            Name = "Noise-Isolating Earbuds",
                            Price = 12.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 1,
                            Description = "10,000mAh USB power bank",
                            ImageUrl = "https://images.unsplash.com/photo-1594843665794-446ce915d840?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cG93ZXIlMjBiYW5rfGVufDB8fDB8fHww",
                            Name = "Portable Power Bank",
                            Price = 29.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 3,
                            Description = "Extended desk-size pad",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1679177183775-75c2e0d0d209?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Z2FtaW5nJTIwbW91c2UlMjBwYWR8ZW58MHx8MHx8fDA%3D",
                            Name = "Gaming Mouse Pad",
                            Price = 15.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 1,
                            Description = "Controls smart devices",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1688686804638-fadb460edc4a?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c21hcnQlMjBob21lfGVufDB8fDB8fHww",
                            Name = "Smart Home Hub",
                            Price = 89.00m,
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 1,
                            Description = "4K output adapter",
                            ImageUrl = "https://m.media-amazon.com/images/I/61kv7aTqB0L.jpg",
                            Name = "USB-C to HDMI Adapter",
                            Price = 16.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 2,
                            Description = "Height-adjustable desk",
                            ImageUrl = "https://images.unsplash.com/photo-1622126755582-16754165dce8?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c3RhbmRpbmclMjBkZXNrfGVufDB8fDB8fHww",
                            Name = "Electric Standing Desk",
                            Price = 349.99m,
                            StockQuantity = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HOT3.Models.Order", b =>
                {
                    b.HasOne("HOT3.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HOT3.Models.OrderItem", b =>
                {
                    b.HasOne("HOT3.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HOT3.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HOT3.Models.Product", b =>
                {
                    b.HasOne("HOT3.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HOT3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HOT3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HOT3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HOT3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HOT3.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HOT3.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HOT3.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
